tenantID: 00000000-0000-0000-0000-000000000000
subscriptionID: 00000000-0000-0000-0000-000000000000

aks:
  name: aks-aso-sample-infra
  rg: rg-aso-sample-infra
  vnet: <look this value up from the Azure Portal>

# Uncomment this if you want to run the code locally using your IP address
# dev:
#   ip: <insert your ip address here>

app:
  name: aso-votes-app
  namespace: default
  image: docker.io/jupflueg/aso-votes-app:latest
  identity:
    name: mi-aso-votes-app
    clientID: 00000000-0000-0000-0000-000000000000

aso:
  clientID: 00000000-0000-0000-0000-000000000000

locations:
  - name: eastus
    failoverPriority: 0
    isZoneRedundant: true
  - name: westus
    failoverPriority: 1
    isZoneRedundant: false
