tenantID: 72f988bf-86f1-41af-91ab-2d7cd011db47
subscriptionID: 7060bca0-7a3c-44bd-b54c-4bb1e9facfac

aks:
  name: aks-aso-sample-infra
  rg: rg-aso-sample-infra
  vnet: aks-vnet-12520612

dev:
  ip: 73.153.28.188

app:
  name: aso-votes-app
  namespace: default
  image: docker.io/jupflueg/aso-votes-app:latest
  identity:
    name: mi-aso-votes-app
    clientID: bd7a0881-1f42-4693-a3c9-6205d9abc8e5

aso:
  clientID: 05a866fa-6ac7-4805-82e5-6b9f6a3a5f41

locations:
  - name: eastus
    failoverPriority: 0
    isZoneRedundant: true
  - name: westus
    failoverPriority: 1
    isZoneRedundant: false
