apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
    name: mi-aso-votes-app
spec:
    type: 0
    resourceID: /subscriptions/7060bca0-7a3c-44bd-b54c-4bb1e9facfac/resourcegroups/rg-aso-votes-app/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mi-aso-votes-app
    clientID: e149f8bd-ba09-4823-95f3-500f6f8e13d7
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
    name: mi-aso-votes-app-binding
spec:
    azureIdentity: mi-aso-votes-app
    selector: mi-aso-votes-app