apiVersion: azure.microsoft.com/v1alpha1
kind: AppInsights
metadata:
  name: appinsights-aso-votes-app
  labels:
    application: aso-votes-app
spec:
  resourceGroup: rg-aso-votes-app
  location: eastus
  kind: other # Values should typically be one of the following: web, ios, other, store, java, phone.
  applicationType: other # Possible values include 'web' or 'other'