apiVersion: azure.microsoft.com/v1alpha1
kind: AppInsights
metadata:
  name: appinsights-sample
spec:
  kind: other # Values should typically be one of the following: web, ios, other, store, java, phone.
  location: southcentralus
  resourceGroup: rg-aso-dev-jp
  applicationType: other # Possible values include 'web' or 'other'