apiVersion: azure.microsoft.com/v1alpha1
kind: CosmosDB
metadata:
  name: cosmos-aso-votes-app
  labels:
    application: aso-votes-app
spec:
  kind: GlobalDocumentDB
  location: eastus
  resourceGroup: rg-aso-votes-app
  properties:
    databaseAccountOfferType: Standard

    enableMultipleWriteLocations: true

    # enable virtual network rules if configured below
    isVirtualNetworkFilterEnabled: true

  # allow access from the AKS cluster it is being deployed to
  virtualNetworkRules:
    #TODO: Replace the following with your own AKS Cluster's subnet Resource ID
    - subnetID: /subscriptions/7060bca0-7a3c-44bd-b54c-4bb1e9facfac/resourceGroups/MC_rg-aso-sample-infra_aks-aso-sample-infra_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-12520612/subnets/aks-subnet
  ipRules:
    # allow access from azure portal
    - 104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26
    #TODO: insert the public IP of your machine here (ex: `curl ifconfig.me`)
    - 73.153.28.188,67.176.114.217

  locations:
    - locationName: eastus
      failoverPriority: 0
      isZoneRedundant: true
    - locationName: westus
      failoverPriority: 1