apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: aso-votes-app
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      application: aso-votes-app
  template:
    metadata:
      labels:
        application: aso-votes-app
    spec:
      containers:
      - name: aso-votes-app
        image: docker.io/jupflueg/aso-votes-app:latest
        ports:
        - containerPort: 8080
        env:
          - name: COSMOSDB_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: cosmos-aso-votes-app
                key: primaryEndpoint
          - name: COSMOSDB_ACCOUNTKEY
            valueFrom:
              secretKeyRef:
                name: cosmos-aso-votes-app
                key: primaryMasterKey
          - name: APPINSIGHTS_INSTKEY
            valueFrom:
              secretKeyRef:
                name: appinsights-aso-votes-app
                key: instrumentationKey
---
apiVersion: v1
kind: Service
metadata:
  name: aso-votes-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    application: aso-votes-app