apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.app.name | quote }}
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      application: {{ .Values.app.name | quote }}
  template:
    metadata:
      labels:
        application: {{ .Values.app.name | quote }}
        aadpodidbinding: {{ .Values.app.name | quote }}
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image | quote }}
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          ports:
            - containerPort: 8080
          env:
            - name: COSMOSDB_SECRET_PATH
              value: "/mnt/secrets-store/{{ .Values.app.namespace }}-cosmos-{{ .Values.app.name }}"
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: "appinsights-{{ .Values.app.name }}"
                  key: "instrumentationKey"
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secretprovider-{{ .Values.app.name }}"