apiVersion: azure.microsoft.com/v1alpha1
kind: AppInsights
metadata:
  name: "appinsights-{{ .Values.app.name }}"
  labels:
    application: {{ .Values.app.name | quote }}
spec:
  resourceGroup: "rg-{{ .Values.app.name }}"
  location: {{ (index .Values.locations 0).name | quote }}
  kind: other
  applicationType: other