apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
    name: {{ .Values.app.identity.name | quote }}
spec:
    type: 0
    resourceID: "/subscriptions/{{ .Values.subscriptionID }}/resourcegroups/rg-{{ .Values.app.name }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{{ .Values.app.identity.name }}"
    clientID: {{ .Values.app.identity.clientID | quote }}