apiVersion: azure.microsoft.com/v1alpha1
kind: KeyVault
metadata:
  name: "kv-{{ .Values.app.name }}"
  labels:
    application: {{ .Values.app.name | quote }}
spec:
  resourceGroup: "rg-{{ .Values.app.name }}"
  location: {{ (index .Values.locations 0).name | quote }}
  enableSoftDelete: false
  sku:
    name: "Standard"
  accessPolicies:
    # allow the aso managed identity to access secrets
    - tenantID: {{ .Values.tenantID | quote }}
      clientID: {{ .Values.aso.clientID | quote }}
      permissions:
        secrets: # backup delete get list purge recover restore set
          - list
          - get
          - delete
          - set