apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "secretprovider-{{ .Values.app.name }}"
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "kv-{{ .Values.app.name }}"
    objects:  |
      array:
        - |
          objectName: "{{ .Values.app.namespace }}-cosmos-{{ .Values.app.name }}"
          objectType: secret
    tenantId: {{ .Values.tenantID | quote }}