apiVersion: v1
kind: Namespace
metadata:
  name: cosmos-todo
---
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: aso-cosmos-demo
  namespace: cosmos-todo
spec:
  location: westcentralus
---
apiVersion: managedidentity.azure.com/v1beta20181130
kind: UserAssignedIdentity
metadata:
  name: cosmos-todo-identity
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: aso-cosmos-demo
  operatorSpec:
    configMaps:
      principalId:
        name: cosmos-todo-identity-settings
        key: principalId
      clientId:
        name: cosmos-todo-identity-settings
        key: clientId
---
apiVersion: managedidentity.azure.com/v1beta20220131preview
kind: FederatedIdentityCredential
metadata:
  name: cosmos-todo-fic
  namespace: cosmos-todo
spec:
  owner:
    name: cosmos-todo-identity
  audiences:
    # For Workload Identity, Audiences should always be "api://AzureADTokenExchange"
    - api://AzureADTokenExchange
  # For Workload Identity, Issuer should be the OIDC endpoint of the cluster. For AKS this will look like
  # https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/
  issuer: ${AKS_OIDC_ISSUER}
  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:cosmos-todo:cosmos-service-account
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: DatabaseAccount
metadata:
  name: cosmostodoacct
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: aso-cosmos-demo
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: westcentralus
  operatorSpec:
    secrets:
      documentEndpoint:
        name: cosmos-connection-settings
        key: documentEndpoint
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabase
metadata:
  name: sample-sql-db
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: cosmostodoacct
  options:
    autoscaleSettings:
      maxThroughput: 4000
  resource:
    id: sample-sql-db
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabaseContainer
metadata:
  name: sample-sql-container
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: sample-sql-db
  resource:
    id: sample-sql-container
    partitionKey:
      kind: Hash
      paths: ["/id"]
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: SqlRoleAssignment
metadata:
  name: cosmos-role-assignment
  namespace: cosmos-todo
spec:
  owner:
    name: cosmostodoacct
  azureName: 31edb778-9702-4f43-a47a-5817594044af # This can be any UUID
  principalIdConfigRef:
    name: cosmos-todo-identity-settings
    key: principalId
  # This RoleDefinition corresponds to "Cosmos DB Built-in Data Contributor". See https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#built-in-role-definitions for more.
  roleDefinitionId: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/cosmos-todo-rg/providers/Microsoft.DocumentDB/databaseAccounts/cosmostodoacct/sqlRoleDefinitions/00000000-0000-0000-0000-000000000002
  scope: /subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/cosmos-todo-rg/providers/Microsoft.DocumentDB/databaseAccounts/cosmostodoacct
