apiVersion: v1
kind: Namespace
metadata:
  name: cosmos-todo
---
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: aso-cosmos-demo
  namespace: cosmos-todo
spec:
  location: westcentralus
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: DatabaseAccount
metadata:
  name: cosmostodoacct
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: aso-cosmos-demo
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: westcentralus
  operatorSpec:
    secrets:
      primaryMasterKey:
        name: cosmos-connection-settings
        key: key
      documentEndpoint:
        name: cosmos-connection-settings
        key: documentEndpoint
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabase
metadata:
  name: sample-sql-db
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: cosmostodoacct
  options:
    autoscaleSettings:
      maxThroughput: 4000
  resource:
    id: sample-sql-db
---
apiVersion: documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabaseContainer
metadata:
  name: sample-sql-container
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: sample-sql-db
  resource:
    id: sample-sql-container
    partitionKey:
      kind: Hash
      paths: ["/id"]
