apiVersion: v1
kind: Namespace
metadata:
  name: cosmos-todo
---
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: ${APP_NAME}-rg
  namespace: cosmos-todo
spec:
  location: westcentralus
---
apiVersion: documentdb.azure.com/v1api20210515
kind: DatabaseAccount
metadata:
  name: $APP_NAME-sqldb
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: ${APP_NAME}-rg
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: westcentralus
  operatorSpec:
    secrets:
      primaryMasterKey:
        name: $APP_NAME-sqldb-connection-settings
        key: key
      documentEndpoint:
        name: $APP_NAME-sqldb-connection-settings
        key: documentEndpoint
---
apiVersion: documentdb.azure.com/v1api20210515
kind: SqlDatabase
metadata:
  name: ${APP_NAME}-sql-db
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: $APP_NAME-sqldb
  options:
    autoscaleSettings:
      maxThroughput: 4000
  resource:
    id: ${APP_NAME}-sql-db
---
apiVersion: documentdb.azure.com/v1api20210515
kind: SqlDatabaseContainer
metadata:
  name: ${APP_NAME}-sql-container
  namespace: cosmos-todo
spec:
  location: westcentralus
  owner:
    name: ${APP_NAME}-sql-db
  resource:
    id: ${APP_NAME}-sql-container
    partitionKey:
      kind: Hash
      paths: ["/id"]
