apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cosmos-todo-app
  name: cosmos-todo-app
  namespace: cosmos-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-todo-app
  template:
    metadata:
      labels:
        app: cosmos-todo-app
    spec:
      containers:
      - name: app
        image: mcr.microsoft.com/k8s/asodemos/cosmostodo:latest
        env:
          - name: CosmosDB__Account
            valueFrom:
              secretKeyRef:
                # This is the secret created by ASO associated with the CosmosDB Account.
                name: ${APP_NAME}-sqldb-connection-settings
                # See https://azure.github.io/azure-service-operator/reference/documentdb/v1api20210515/#documentdb.azure.com/v1api20210515.DatabaseAccount for more details
                key: documentEndpoint
                optional: false
          - name: CosmosDB__Key
            valueFrom:
              secretKeyRef:
                key: key
                # This is the secret created by ASO associated with the CosmosDB Account.
                name: ${APP_NAME}-sqldb-connection-settings
                # See https://azure.github.io/azure-service-operator/reference/documentdb/v1api20210515/#documentdb.azure.com/v1api20210515.DatabaseAccount for more details
                optional: false
          - name: CosmosDB__DatabaseName
            value: "${APP_NAME}-sql-db"
          - name: CosmosDB__ContainerName
            value: "${APP_NAME}-sql-container"
        ports:
        - containerPort: 80
          name: webserver
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cosmos-todo-service
  namespace: cosmos-todo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cosmos-todo-app
