apiVersion: v1
kind: Namespace
metadata:
  name: cosmosdb
---
apiVersion: microsoft.resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: aso-cosmos-demo
  namespace: cosmosdb
spec:
  location: westcentralus
---
apiVersion: microsoft.documentdb.azure.com/v1alpha1api20210515
kind: DatabaseAccount
metadata:
  name: sampledbaccount
  namespace: cosmosdb
spec:
  location: westcentralus
  owner:
    name: aso-cosmos-demo
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: westcentralus
---
apiVersion: microsoft.documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabase
metadata:
  name: sample-sql-db
  namespace: cosmosdb
spec:
  location: westcentralus
  owner:
    name: sampledbaccount
  options:
    autoscaleSettings:
      maxThroughput: 4000
  resource:
    id: sample-sql-db
---
apiVersion: microsoft.documentdb.azure.com/v1alpha1api20210515
kind: SqlDatabaseContainer
metadata:
  name: sample-sql-container
  namespace: cosmosdb
spec:
  location: westcentralus
  owner:
    name: sample-sql-db
  resource:
    id: sample-sql-container
    partitionKey:
      kind: Hash
      paths: ["/id"]
